version: '2'

services:
  web:
    build:
      context: ./
    links:
      - mysql
      - redis
    ports:
      - '80'
    volumes:
      - ./shared/:/var/www/packagist/shared/
    environment:
      - VIRTUAL_HOST=packagist.test
    network_mode: bridge

  mysql:
    image: percona:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=packagist
      - MYSQL_USER=packagist
      - MYSQL_PASSWORD=packagist
    network_mode: bridge

  redis:
    restart: always
    image: redis:latest
    network_mode: bridge