.catalog:
  name: "Packagist"
  version: "1.0.0"
  description: "Package Repository Website for Composer"
  questions:
    - variable: virtual_host
      label: "Virtual Host"
      required: true
      type: "string"
    - variable: path_to_shared_files
      label: "Path To Shared Files"
      required: true
      type: "string"
    - variable: ssh_public_key
      label: "SSH Public Key"
      required: false
      type: "multiline"
      default: ""
    - variable: ssh_private_key
      label: "SSH Private Key"
      required: false
      type: "multiline"
      default: ""